/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as AdminadminRouteImport } from './routes/adminadmin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealsSlugRouteImport } from './routes/deals.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminadminRoute = AdminadminRouteImport.update({
  id: '/adminadmin',
  path: '/adminadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsSlugRoute = DealsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DealsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminadmin': typeof AdminadminRoute
  '/deals': typeof DealsRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/deals/$slug': typeof DealsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminadmin': typeof AdminadminRoute
  '/deals': typeof DealsRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/deals/$slug': typeof DealsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adminadmin': typeof AdminadminRoute
  '/deals': typeof DealsRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/deals/$slug': typeof DealsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminadmin'
    | '/deals'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/deals/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adminadmin'
    | '/deals'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/deals/$slug'
  id:
    | '__root__'
    | '/'
    | '/adminadmin'
    | '/deals'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/deals/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminadminRoute: typeof AdminadminRoute
  DealsRoute: typeof DealsRouteWithChildren
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminadmin': {
      id: '/adminadmin'
      path: '/adminadmin'
      fullPath: '/adminadmin'
      preLoaderRoute: typeof AdminadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$slug': {
      id: '/deals/$slug'
      path: '/$slug'
      fullPath: '/deals/$slug'
      preLoaderRoute: typeof DealsSlugRouteImport
      parentRoute: typeof DealsRoute
    }
  }
}

interface DealsRouteChildren {
  DealsSlugRoute: typeof DealsSlugRoute
}

const DealsRouteChildren: DealsRouteChildren = {
  DealsSlugRoute: DealsSlugRoute,
}

const DealsRouteWithChildren = DealsRoute._addFileChildren(DealsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminadminRoute: AdminadminRoute,
  DealsRoute: DealsRouteWithChildren,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
